development:
  adapter: mysql2
  encoding: utf8
  database: development_jovemprogramador
  username: root
  password:
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: test_jovemprogramador
  username: root
  password:
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: jovemprogramador
  username: root
  password:
  host: localhost
  port: 3306
